GET http://localhost:5000/chat

###

POST http://localhost:5000/chat
Content-Type: application/json

{
    "chatId": 1,
    "message": "To seoul"
}

###

DELETE http://localhost:5000/chat/1

###

GET http://localhost:5000/chat/ses