GET http://localhost:3000/chat

###

POST http://localhost:3000/chat
Content-Type: application/json

{
    "chatId": 1,
    "message": "Give me some more"
}

###

DELETE http://localhost:3000/chat/1

###

GET http://localhost:3000/chat/sse?chatId=1
